apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  namespace: efs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      name: myapp1-pod
      labels:
        app: myapp1
    spec:
      containers:
        - name: myapp1-container
          image: stacksimplify/kubenginx:1.0.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: persistent-storage
              mountPath: /usr/share/nginx/html/efs
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-claim
---

apiVersion: v1
kind: Service
metadata:
  name: myapp1-service
  namespace: efs
spec:
  selector:
    app: myapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

