apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
  namespace: efs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      name: myapp2-pod
      labels:
        app: myapp2
    spec:
      containers:
        - name: myapp1-container
          image: stacksimplify/kubenginx:1.0.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: persistent-storage
              mountPath: /usr/share/nginx/html/app2
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-claim