apiVersion: v1
kind: Pod
metadata:
  name: efs-write-app
  namespace: efs
spec:
  containers:
    - name: efs-write-app
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo EFS Kubernetes Dynamic Provisioning Test $(date -u) >> /data/efs-dynamic.txt; sleep 5; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-claim
